"""empty message

Revision ID: 488c5edf39e2
Revises: 
Create Date: 2023-03-07 10:14:27.427809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '488c5edf39e2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news',
    sa.Column('newsId', sa.Integer(), nullable=False),
    sa.Column('newsTitle', sa.String(length=100), nullable=False),
    sa.Column('publicDate', sa.String(length=50), nullable=False),
    sa.Column('sourceWebsite', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('newsId')
    )
    op.create_table('stock',
    sa.Column('stockId', sa.Integer(), nullable=False),
    sa.Column('tradeDate', sa.Float(), nullable=False),
    sa.Column('openPrice', sa.Float(), nullable=False),
    sa.Column('highestPrice', sa.Float(), nullable=False),
    sa.Column('lowestPrice', sa.Float(), nullable=False),
    sa.Column('closePrice', sa.Float(), nullable=False),
    sa.Column('yesterday_closePrice', sa.Float(), nullable=False),
    sa.Column('changeAmount', sa.Float(), nullable=False),
    sa.Column('changeAmplitude', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('turnover', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('stockId')
    )
    op.create_table('user',
    sa.Column('userId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('userName', sa.String(length=16), nullable=False),
    sa.Column('password', sa.String(length=20), nullable=False),
    sa.Column('userMail', sa.String(length=30), nullable=False),
    sa.Column('nickname', sa.String(length=20), nullable=True),
    sa.Column('profilePhoto', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('userId')
    )
    op.create_table('subscription',
    sa.Column('sub_userId', sa.Integer(), nullable=False),
    sa.Column('sub_stockId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sub_stockId'], ['stock.stockId'], ),
    sa.ForeignKeyConstraint(['sub_userId'], ['user.userId'], ),
    sa.PrimaryKeyConstraint('sub_userId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscription')
    op.drop_table('user')
    op.drop_table('stock')
    op.drop_table('news')
    # ### end Alembic commands ###
