"""empty message

Revision ID: b0ffdbc816e6
Revises: 488c5edf39e2
Create Date: 2023-03-08 10:27:28.470845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0ffdbc816e6'
down_revision = '488c5edf39e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('signature', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('signature')
        batch_op.drop_column('age')

    # ### end Alembic commands ###
